### ISSUE TITLE
ArgumentError, "header #{key} has field value #{value.inspect}, this cannot include CR/LF"

### ISSUE THREAD

**Issue by rdh** [buildkite/test-collector-ruby#122]
I'm getting the following exception after naively copying the API token from the website into GitHub secrets and then setting in ENV for my GitHub action...

```
An error occurred in a `before(:suite)` hook.
Failure/Error: raise ArgumentError, "header #{key} has field value #{value.inspect}, this cannot include CR/LF"
ArgumentError:
  header Authorization has field value "Token token=\"***\n\n\"", this cannot include CR/LF
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/net/http/header.rb:23:in `block in initialize_http_header'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/net/http/header.rb:16:in `each'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/net/http/header.rb:16:in `initialize_http_header'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/net/http/generic_request.rb:46:in `initialize'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/net/http/request.rb:15:in `initialize'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/http_client.rb:19:in `new'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/http_client.rb:19:in `post'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/uploader.rb:[42](https://github.com/yankaindustries/masterclass/runs/6871164066?check_suite_focus=true#step:7:43):in `configure'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/library_hooks/rspec.rb:16:in `block (2 levels) in <top (required)>'
```

I was able to work around this by manually pulling the token from ENV, stripping it, and passing to Buildkite...
```
Buildkite::TestCollector.configure(hook: :rspec, token: ENV['BUILDKITE_ANALYTICS_TOKEN']&.strip )
```

You may want to `strip` when you load the ENV var, just to give other folks who run into this a slightly smoother onboarding, at https://github.com/buildkite/test-collector-ruby/blob/8637fdc9f3a57d4059c9f71123ee99bd0468fe17/lib/buildkite/test_collector.rb#L26 

You may also want to check your website to see if the "copy" icon is loading the token into the copy buffer with appended newline.

**Comment by gchan** [comment]
Hi @rdh ! 

Adding `&.strip` to some of envars seems like a reasonable thing for us to do! We will patch this up soon! 

A few members of our team tried to reproduce the 'copy' issue on our end. Could you provide us with details on which browser and OS you were using?

Thanks!

**Comment by gchan** [comment]
@rdh we merged https://github.com/buildkite/test-collector-ruby/pull/127 to main . Please give that a go and let us know whether it resolves this issue! You can pull down the latest changes from `main` in your Gemfile like so:

```
gem "buildkite-test_collector", git: "git@github.com:buildkite/test-collector-ruby.git", branch: "main"
```

**Comment by rdh** [comment]
> Hi @rdh !
> 
> Adding `&.strip` to some env vars seems like a reasonable thing for us to do! We will patch this up soon!
> 
> A few members of our team tried to reproduce the 'copy' issue on our end. Could you provide us with details on which browser and OS you were using?
> 
> Thanks!
<img width="698" alt="Screen Shot 2022-06-21 at 1 16 34 PM" src="https://user-images.githubusercontent.com/306352/174889709-ac893fe3-d0f9-4c61-a500-40e17c6755c3.png">
<img width="397" alt="Screen Shot 2022-06-21 at 1 16 17 PM" src="https://user-images.githubusercontent.com/306352/174889727-9f849302-905e-4683-b36d-56f6a7f8ff65.png">
