### ISSUE TITLE
Buildkite::TestCollector::SocketConnection::HandshakeError results in a failed build

### ISSUE THREAD

**Issue by rdh** [buildkite/test-collector-ruby#138]
We observed the following failure around July 4, 12:56am PDT...

```
bundler: failed to load command: rspec (/home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bin/rspec)
Coverage report generated for RSpec to /home/runner/work/masterclass/masterclass/backend/coverage. 30423 / 55154 LOC (55.16%) covered.
/home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/socket_connection.rb:60:in `initialize': :invalid_status_code (Buildkite::TestCollector::SocketConnection::HandshakeError)
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/session.rb:161:in `new'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/session.rb:161:in `connect'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/session.rb:75:in `block in disconnected'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/session.rb:58:in `synchronize'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/session.rb:58:in `disconnected'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/socket_connection.rb:86:in `rescue in block in initialize'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/socket_connection.rb:69:in `block in initialize'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/openssl/buffering.rb:125:in `sysread': end of file reached (EOFError)
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/openssl/buffering.rb:125:in `readpartial'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/socket_connection.rb:73:in `block in initialize'
```

This one was benign, but a build/test failure blocks our deploy process, which we treat as an incident.  Quick fix, I'm going to pull BKTA our of our CI pipeline, so we don't have an external service vulnerability.  

It would be great if you could "fail and warn" rather than fail the entire test process.  Or maybe add a config for soft vs hard fails from BK internals?

**Comment by rdh** [comment]
At around 2:24am that same morning, we had another mysterious exception out of BKTA...

```
bundler: failed to load command: rspec (/home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bin/rspec)
/home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:143:in `block in and_raise': JSON::ParserError (JSON::ParserError)
Coverage report generated for RSpec to /home/runner/work/masterclass/masterclass/backend/coverage. 31753 / 55195 LOC (57.53%) covered.
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:694:in `block in call'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:693:in `map'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:693:in `call'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:572:in `invoke_incrementing_actual_calls_by'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:427:in `invoke'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/proxy.rb:214:in `message_received'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/proxy.rb:361:in `message_received'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/method_double.rb:78:in `proxy_method_invoked'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/session.rb:125:in `handle'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/buildkite-test_collector-1.0.1/lib/buildkite/test_collector/socket_connection.rb:76:in `block in initialize'
Error: Process completed with exit code 1.
```

**Comment by gchan** [comment]
Thanks for reporting this to us @rdh .  

The handshake error in your first message was related to an incident https://www.buildkitestatus.com/incidents/ycxf5tdr8xq5

The next two messages relate to a `JSON::ParserError`. It looks like the JSON.parse method might be mocked by Rspec? 
Is your codebase potentially mocking/stubbing the JSON module? 
 
Can you also give version 1.1.1 of the gem a go?

**Comment by rdh** [comment]
I've given our RSpecs a quick grep and do not see any instances of us mocking `JSON.parse`.  Possible I missed something, but given placement and timing, suspect a bogus response from your server, or possibly an intervening nginx, Cloudflare, AWS, or something.

RE: 1.1.1, unfortunately, our free trial ran out and our test volume is large enough (projected 10m/month), that I'll need to get budget approval.  I can upgrade the gem, but we've backed this off our main CI flow and won't see data in the dashboard, so not sure how much value that will be.  FWIW, we're back-burnering this eval and hope to kick the tires again in a month when our free trial resets.

**Comment by gchan** [comment]
@rdh I've spoke to the team about your helpful feedback and valuable contributions. So we've extended your business trail for 3 more weeks (your trial will now end on July 30).

**Comment by rdh** [comment]
> @rdh I've spoken to the team about your helpful feedback and valuable contributions. So we've extended your business trail for 3 more weeks (your trial will now end on July 30).

Thanks @gchan !  Appreciate it.

I just put in a PR to upgrade to 1.1.1 which should get approval and merge tomorrow.  We're keeping it out of main CI flow, but have it enabled in a sanity checker that runs every 30 mins.  I'll update https://github.com/buildkite/test-collector-ruby/issues/135 once I do (or don't) see the branch filtering properly in the dashboard.

**Comment by gchan** [comment]
@rdh Are you still experiencing the JSON::ParserErrors? Were these intermittent issues?

**Comment by rdh** [comment]
The JSON parse errors were intermittent, but we encountered another on 7/7/22 at 8am PT.  Have not seen one since.

**Comment by gchan** [comment]
Let us know whether it comes up again for you on the latest version of this gem. If you are successfully running it every 30 mins, it may no longer be an issue. :)

**Comment by rdh** [comment]
Just FYI, we encountered another one of these at 1:20 PM PT today.  Opening a ticket on our end to attempt to repro and make sure our code isn't doing something funny.  Passed the previous sniff test, but curious to see if we can repro.

**Comment by rdh** [comment]
Here's the most recent stack trace.  All of our specs have completed successfully before this occurs...

```
Finished in 24 minutes 40 seconds (files took 19.01 seconds to load)
3245 examples, 0 failures, 86 pending
bundler: failed to load command: rspec (/home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bin/rspec)
Coverage report generated for RSpec to /home/runner/work/masterclass/masterclass/backend/coverage. 30553 / 55417 LOC (55.13%) covered.
/home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:143:in `block in and_raise': JSON::ParserError (JSON::ParserError)
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:694:in `block in call'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:693:in `map'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:693:in `call'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:572:in `invoke_incrementing_actual_calls_by'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/message_expectation.rb:427:in `invoke'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/proxy.rb:214:in `message_received'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/proxy.rb:361:in `message_received'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/method_double.rb:78:in `proxy_method_invoked'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-mocks-3.10.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-2a28da732521/lib/buildkite/test_collector/session.rb:125:in `handle'
	from /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-2a28da732521/lib/buildkite/test_collector/socket_connection.rb:76:in `block in initialize'
Error: Process completed with exit code 1.
```

The stack trace looks like it could be a dangling mock/stub of some kind, but did not grep up any previous stubbing of `JSON.parse` in our code, but I would expect al stubs to be torn down by this point?  And just did a triple-check based on this stack trace.    

I also re-ran with the same commit hash and seed, and it did not repro, so it at least smells a bit like a network issue, although it's odd that it's failing down in `rspec-mocks` ... we also use `webmock` and `vcr` gems.  Could be a clue.  But very odd how sporadic this is, which smells even more like a network issue.

**Comment by rdh** [comment]
Just FYI, we had another one of these reported at 6:11am PT this morning.  

It would be interesting to add an exception catch around that bit of code for this one (looks like there's [already a bunch in there](https://github.com/buildkite/test-collector-ruby/blob/main/lib/buildkite/test_collector/socket_connection.rb#L76-L107)) to log the bogus response.  My current theory is that an empty buffer is occasionally sneaking back from the socket for some reason, but perhaps there's still a network mock in place returning "something else"?

If I find some free time this weekend, may fork your repo, and add that logging.  Would you be willing/able to kick us a bit more free trial in exchange for said effort?  Will be easier to chase budget approval with "no known issues" 😈

**Comment by gchan** [comment]
@rdh I've created a branch which rescues the exception and logs the contents of `data` to help with your debugging.

https://github.com/buildkite/test-collector-ruby/tree/rdh-json-parse-error
You can point your Gemfile to use this branch `branch: 'rdh-json-parse-error'`

I understand you still have a trail to the 30th of July, but if you require more time I can make a request to the team.

**Comment by rdh** [comment]
> branch: 'rdh-json-parse-error'

Thank you so much.  Just put in a PR to use the gem from the branch.  These seem to be happening on a slightly more than weekly frequency.  Will keep an eye out for the next one.

**Comment by rdh** [comment]
I feel like I've unfortunately munged two different type of network errors in one issue.  We may want to open a new one for either the original `HandshakeError` or the `JSON::ParseError` most of this thread has been about?

With that, the original `HandshakeError` was detected again at 4:57pm PT.  This time, at the beginning of a run, rather than at the end, although I doubt that makes a difference.
```
An error occurred in a `before(:suite)` hook.
Failure/Error: raise HandshakeError.new(handshake.error.inspect)
Buildkite::TestCollector::SocketConnection::HandshakeError:
  :invalid_status_code
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-8074177c0faf/lib/buildkite/test_collector/socket_connection.rb:56:in `initialize'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-8074177c0faf/lib/buildkite/test_collector/session.rb:159:in `new'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-8074177c0faf/lib/buildkite/test_collector/session.rb:159:in `connect'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-8074177c0faf/lib/buildkite/test_collector/session.rb:41:in `initialize'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-8074177c0faf/lib/buildkite/test_collector/uploader.rb:41:in `new'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-8074177c0faf/lib/buildkite/test_collector/uploader.rb:41:in `configure'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bundler/gems/test-collector-ruby-8074177c0faf/lib/buildkite/test_collector/library_hooks/rspec.rb:15:in `block (2 levels) in <top (required)>'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:365:in `run'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2144:in `block in run_suite_hooks'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2142:in `each'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2142:in `run_suite_hooks'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2066:in `with_suite_hooks'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bin/rspec:23:in `load'
# /home/runner/work/masterclass/masterclass/backend/vendor/bundle/ruby/2.7.0/bin/rspec:23:in `<top (required)>'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.[32](https://github.com/yankaindustries/masterclass/runs/7477065315?check_suite_focus=true#step:8:33)/lib/bundler/cli/exec.rb:58:in `load'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/exe/bundle:[37](https://github.com/yankaindustries/masterclass/runs/7477065315?check_suite_focus=true#step:8:38):in `<top (required)>'
# /opt/hostedtoolcache/Ruby/2.7.6/x[64](https://github.com/yankaindustries/masterclass/runs/7477065315?check_suite_focus=true#step:8:65)/bin/bundle:23:in `load'
# /opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'
# 
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

**Comment by rdh** [comment]
Moving the `JSON::ParseError` discussion over to https://github.com/buildkite/test-collector-ruby/issues/144 to keep this one matching its title.

**Comment by niceking** [comment]
Closing as we have dropped sending test data via websockets as of v2.1.0 and are no longer supporting older versions of the ruby test collector which still use websockets. Users experiencing this issue will need to upgrade to the latest version of the ruby test collector
