### ISSUE TITLE
allow_any_instance_of(<class>).to receive(:<method_name?>) failure

### ISSUE THREAD

**Issue by kphatak** [buildkite/test-collector-ruby#142]
### Env
``` ~/git/api/ [master] bundle exec rspec --version
RSpec 3.9
  - rspec-core 3.9.1
  - rspec-expectations 3.9.1
  - rspec-mocks 3.9.1
  - rspec-rails 3.9.1
  - rspec-support 3.9.2
 ~/git/api/ [master] bundle exec ruby --version
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin21]
```

### Error

```
Failures:
  1) Users Managing users POST /staff/users create a user with valid params
     Failure/Error:
       allow_any_instance_of(::RBAC::Client).to receive(:build_http_client)
 
       RBAC::Client does not implement #build_http_client
     # ./spec/requests/staff/users_spec.rb:229:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/buildkite-test_collector-1.1.1/lib/buildkite/test_collector/library_hooks/rspec.rb:25:in `block (2 levels) in <top (required)>'
```

This looks related to https://github.com/buildkite/test-collector-ruby/issues/123 but we are already stubbing the class.
I would appreciate any help. TIA.

**Comment by kphatak** [comment]
Nvm. Code issue. Fixed.
